/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FieldsRouteImport } from './routes/fields'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as ClaimsIndexRouteImport } from './routes/claims.index'
import { Route as ClaimsIdRouteImport } from './routes/claims.$id'
import { Route as FieldsIndexRouteImport } from './routes/fields.index'
import { Route as FieldsIdRouteImport } from './routes/fields.$id'
import { Route as FieldsNewRouteImport } from './routes/fields.new'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosIdRouteImport } from './routes/videos.$id'
import { Route as WildlifeIndexRouteImport } from './routes/wildlife.index'
import { Route as WildlifeSpeciesRouteImport } from './routes/wildlife.$species'
import { Route as VideosIdIndexRouteImport } from './routes/videos.$id.index'
import { Route as VideosIdProcessingRouteImport } from './routes/videos.$id.processing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsRoute = FieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsIndexRoute = ClaimsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClaimsRoute,
} as any)
const ClaimsIdRoute = ClaimsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClaimsRoute,
} as any)
const FieldsIndexRoute = FieldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FieldsRoute,
} as any)
const FieldsIdRoute = FieldsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FieldsRoute,
} as any)
const FieldsNewRoute = FieldsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FieldsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosRoute,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VideosRoute,
} as any)
const WildlifeIndexRoute = WildlifeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WildlifeRoute,
} as any)
const WildlifeSpeciesRoute = WildlifeSpeciesRouteImport.update({
  id: '/$species',
  path: '/$species',
  getParentRoute: () => WildlifeRoute,
} as any)
const VideosIdIndexRoute = VideosIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VideosIdRoute,
} as any)
const VideosIdProcessingRoute = VideosIdProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => VideosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/ask': typeof AskRoute
  '/claims': typeof ClaimsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fields': typeof FieldsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRouteWithChildren
  '/wildlife': typeof WildlifeRouteWithChildren
  '/claims/$id': typeof ClaimsIdRoute
  '/fields/$id': typeof FieldsIdRoute
  '/fields/new': typeof FieldsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/videos/$id': typeof VideosIdRouteWithChildren
  '/wildlife/$species': typeof WildlifeSpeciesRoute
  '/claims/': typeof ClaimsIndexRoute
  '/fields/': typeof FieldsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/wildlife/': typeof WildlifeIndexRoute
  '/videos/$id/processing': typeof VideosIdProcessingRoute
  '/videos/$id/': typeof VideosIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/claims/$id': typeof ClaimsIdRoute
  '/fields/$id': typeof FieldsIdRoute
  '/fields/new': typeof FieldsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/wildlife/$species': typeof WildlifeSpeciesRoute
  '/claims': typeof ClaimsIndexRoute
  '/fields': typeof FieldsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/videos': typeof VideosIndexRoute
  '/wildlife': typeof WildlifeIndexRoute
  '/videos/$id/processing': typeof VideosIdProcessingRoute
  '/videos/$id': typeof VideosIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/ask': typeof AskRoute
  '/claims': typeof ClaimsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fields': typeof FieldsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRouteWithChildren
  '/wildlife': typeof WildlifeRouteWithChildren
  '/claims/$id': typeof ClaimsIdRoute
  '/fields/$id': typeof FieldsIdRoute
  '/fields/new': typeof FieldsNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/videos/$id': typeof VideosIdRouteWithChildren
  '/wildlife/$species': typeof WildlifeSpeciesRoute
  '/claims/': typeof ClaimsIndexRoute
  '/fields/': typeof FieldsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/wildlife/': typeof WildlifeIndexRoute
  '/videos/$id/processing': typeof VideosIdProcessingRoute
  '/videos/$id/': typeof VideosIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/api-docs'
    | '/ask'
    | '/claims'
    | '/dashboard'
    | '/fields'
    | '/login'
    | '/onboarding'
    | '/reports'
    | '/review'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wildlife'
    | '/claims/$id'
    | '/fields/$id'
    | '/fields/new'
    | '/reports/$id'
    | '/videos/$id'
    | '/wildlife/$species'
    | '/claims/'
    | '/fields/'
    | '/reports/'
    | '/videos/'
    | '/wildlife/'
    | '/videos/$id/processing'
    | '/videos/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/api-docs'
    | '/ask'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/review'
    | '/settings'
    | '/upload'
    | '/claims/$id'
    | '/fields/$id'
    | '/fields/new'
    | '/reports/$id'
    | '/wildlife/$species'
    | '/claims'
    | '/fields'
    | '/reports'
    | '/videos'
    | '/wildlife'
    | '/videos/$id/processing'
    | '/videos/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/api-docs'
    | '/ask'
    | '/claims'
    | '/dashboard'
    | '/fields'
    | '/login'
    | '/onboarding'
    | '/reports'
    | '/review'
    | '/settings'
    | '/upload'
    | '/videos'
    | '/wildlife'
    | '/claims/$id'
    | '/fields/$id'
    | '/fields/new'
    | '/reports/$id'
    | '/videos/$id'
    | '/wildlife/$species'
    | '/claims/'
    | '/fields/'
    | '/reports/'
    | '/videos/'
    | '/wildlife/'
    | '/videos/$id/processing'
    | '/videos/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AskRoute: typeof AskRoute
  ClaimsRoute: typeof ClaimsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FieldsRoute: typeof FieldsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRouteWithChildren
  WildlifeRoute: typeof WildlifeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields': {
      id: '/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof FieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims/': {
      id: '/claims/'
      path: '/'
      fullPath: '/claims/'
      preLoaderRoute: typeof ClaimsIndexRouteImport
      parentRoute: typeof ClaimsRoute
    }
    '/claims/$id': {
      id: '/claims/$id'
      path: '/$id'
      fullPath: '/claims/$id'
      preLoaderRoute: typeof ClaimsIdRouteImport
      parentRoute: typeof ClaimsRoute
    }
    '/fields/': {
      id: '/fields/'
      path: '/'
      fullPath: '/fields/'
      preLoaderRoute: typeof FieldsIndexRouteImport
      parentRoute: typeof FieldsRoute
    }
    '/fields/$id': {
      id: '/fields/$id'
      path: '/$id'
      fullPath: '/fields/$id'
      preLoaderRoute: typeof FieldsIdRouteImport
      parentRoute: typeof FieldsRoute
    }
    '/fields/new': {
      id: '/fields/new'
      path: '/new'
      fullPath: '/fields/new'
      preLoaderRoute: typeof FieldsNewRouteImport
      parentRoute: typeof FieldsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/videos/': {
      id: '/videos/'
      path: '/'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof VideosRoute
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof VideosRoute
    }
    '/wildlife/': {
      id: '/wildlife/'
      path: '/'
      fullPath: '/wildlife/'
      preLoaderRoute: typeof WildlifeIndexRouteImport
      parentRoute: typeof WildlifeRoute
    }
    '/wildlife/$species': {
      id: '/wildlife/$species'
      path: '/$species'
      fullPath: '/wildlife/$species'
      preLoaderRoute: typeof WildlifeSpeciesRouteImport
      parentRoute: typeof WildlifeRoute
    }
    '/videos/$id/': {
      id: '/videos/$id/'
      path: '/'
      fullPath: '/videos/$id/'
      preLoaderRoute: typeof VideosIdIndexRouteImport
      parentRoute: typeof VideosIdRoute
    }
    '/videos/$id/processing': {
      id: '/videos/$id/processing'
      path: '/processing'
      fullPath: '/videos/$id/processing'
      preLoaderRoute: typeof VideosIdProcessingRouteImport
      parentRoute: typeof VideosIdRoute
    }
  }
}

interface ClaimsRouteChildren {
  ClaimsIdRoute: typeof ClaimsIdRoute
  ClaimsIndexRoute: typeof ClaimsIndexRoute
}

const ClaimsRouteChildren: ClaimsRouteChildren = {
  ClaimsIdRoute: ClaimsIdRoute,
  ClaimsIndexRoute: ClaimsIndexRoute,
}

const ClaimsRouteWithChildren =
  ClaimsRoute._addFileChildren(ClaimsRouteChildren)

interface FieldsRouteChildren {
  FieldsIdRoute: typeof FieldsIdRoute
  FieldsNewRoute: typeof FieldsNewRoute
  FieldsIndexRoute: typeof FieldsIndexRoute
}

const FieldsRouteChildren: FieldsRouteChildren = {
  FieldsIdRoute: FieldsIdRoute,
  FieldsNewRoute: FieldsNewRoute,
  FieldsIndexRoute: FieldsIndexRoute,
}

const FieldsRouteWithChildren =
  FieldsRoute._addFileChildren(FieldsRouteChildren)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface VideosIdRouteChildren {
  VideosIdProcessingRoute: typeof VideosIdProcessingRoute
  VideosIdIndexRoute: typeof VideosIdIndexRoute
}

const VideosIdRouteChildren: VideosIdRouteChildren = {
  VideosIdProcessingRoute: VideosIdProcessingRoute,
  VideosIdIndexRoute: VideosIdIndexRoute,
}

const VideosIdRouteWithChildren = VideosIdRoute._addFileChildren(
  VideosIdRouteChildren,
)

interface VideosRouteChildren {
  VideosIdRoute: typeof VideosIdRouteWithChildren
  VideosIndexRoute: typeof VideosIndexRoute
}

const VideosRouteChildren: VideosRouteChildren = {
  VideosIdRoute: VideosIdRouteWithChildren,
  VideosIndexRoute: VideosIndexRoute,
}

const VideosRouteWithChildren =
  VideosRoute._addFileChildren(VideosRouteChildren)

interface WildlifeRouteChildren {
  WildlifeSpeciesRoute: typeof WildlifeSpeciesRoute
  WildlifeIndexRoute: typeof WildlifeIndexRoute
}

const WildlifeRouteChildren: WildlifeRouteChildren = {
  WildlifeSpeciesRoute: WildlifeSpeciesRoute,
  WildlifeIndexRoute: WildlifeIndexRoute,
}

const WildlifeRouteWithChildren = WildlifeRoute._addFileChildren(
  WildlifeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ApiDocsRoute: ApiDocsRoute,
  AskRoute: AskRoute,
  ClaimsRoute: ClaimsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FieldsRoute: FieldsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRouteWithChildren,
  WildlifeRoute: WildlifeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
